In [178]:
import pandas as pd
from sqlalchemy import create_engine
from functools import reduce
import requests

In [180]:
def get_database():
    """
    Function to connect to the database.
    The file must be called raw_data_project_m1.db and has to be in the data folder.
    """
    print('connecting to the database...')
    db_path = '../data/raw_data_project_m1.db'
    conn_str = f'sqlite:///{db_path}'
    engine = create_engine(conn_str)
    table_names = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)
    tables_names_lst = table_names['name'].to_list()
    all_dfs = [pd.read_sql_query(f'select * from {i}', engine) for i in tables_names_lst]
    merged_tables = reduce(lambda left, right: pd.merge(left, right, on='uuid'), all_dfs)
    print('connected!')
    return merged_tables


get_database()

connecting to the database...
connected!

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,AT,countryside,no,no,None,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,AT,city,None,no,None,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,AT,Country,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,AT,city,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,SK,Non-Rural,low,no,None,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,SK,city,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,SK,city,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [88]:
db_path = '../data/raw_data_project_m1.db'

conn_str = f'sqlite:///{db_path}'

engine = create_engine(conn_str)

In [89]:
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)

            name
0  personal_info
1   country_info
2    career_info
3      poll_info

In [92]:
table_names = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)
tables_names_lst = table_names['name'].to_list()

all_dfs = [pd.read_sql_query(f'select * from {i}', engine) for i in tables_names_lst]
merged_tables = reduce(lambda left, right: pd.merge(left, right, on='uuid'), all_dfs)

merged_tables

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,AT,countryside,no,no,None,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,AT,city,None,no,None,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,AT,Country,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,AT,city,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,SK,Non-Rural,low,no,None,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,SK,city,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,SK,city,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [13]:
pd.read_sql_query("SELECT * from personal_info LIMIT 20",engine)

,uuid,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65
5,28583060-dbe2-0133-ff9c-0a81e8b09a82,1990,FeMale,NO,26_39
6,b50dbb80-da53-0133-8956-0a81e8b09a82,1990,Fem,NO,26_39
7,dd743bb0-d9a5-0133-53b2-0a81e8b09a82,47 years old,Male,NO,40_65
8,4fde2370-da48-0133-3a42-0a81e8b09a82,34 years old,FeMale,nO,26_39
9,9949c4c0-da5f-0133-c832-0a81e8b09a82,1994,female,yES,juvenile
10,226cf850-db28-0133-c51a-0a81e8b09a82,49 years old,male,NO,40_65
11,69f1f400-dc5f-0133-ad9b-0a81e8b09a82,58 years old,male,YES,40_65
12,2351fbe0-de4c-0133-0d58-0a81e8b09a82,1991,female,NO,14_25
13,0f286c80-dd77-0133-7803-0a81e8b09a82,40 years old,male,YES,40_65
14,fe54f360-db27-0133-c444-0a81e8b09a82,37 years old,male,NO,26_39
15,960b1ce0-db01-0133-528c-0a81e8b09a82,48 years old,male,YES,40_65
16,d7912480-da41-0133-5bc1-0a81e8b09a82,31 years old,male,yES,26_39
17,d468c670-da40-0133-de39-0a81e8b09a82,1990,female,NO,26_39
18,76767d10-dd6c-0133-f56d-0a81e8b09a82,1999,female,nO,14_25
19,a96ed910-de55-0133-2582-0a81e8b09a82,34 years old,male,YES,26_39

In [14]:
pd.read_sql_query("SELECT * from country_info LIMIT 20",engine)

                                    uuid country_code        rural
0   f6e7ee00-deac-0133-4de8-0a81e8b09a82           AT  countryside
1   54f0f1c0-dda1-0133-a559-0a81e8b09a82           AT        urban
2   83127080-da3d-0133-c74f-0a81e8b09a82           AT         city
3   15626d40-db13-0133-ea5c-0a81e8b09a82           AT      Country
4   24954a70-db98-0133-4a64-0a81e8b09a82           AT         city
5   28583060-dbe2-0133-ff9c-0a81e8b09a82           AT  countryside
6   b50dbb80-da53-0133-8956-0a81e8b09a82           AT        urban
7   dd743bb0-d9a5-0133-53b2-0a81e8b09a82           AT        urban
8   4fde2370-da48-0133-3a42-0a81e8b09a82           AT         city
9   9949c4c0-da5f-0133-c832-0a81e8b09a82           AT        urban
10  226cf850-db28-0133-c51a-0a81e8b09a82           AT        urban
11  69f1f400-dc5f-0133-ad9b-0a81e8b09a82           AT         city
12  2351fbe0-de4c-0133-0d58-0a81e8b09a82           AT        urban
13  0f286c80-dd77-0133-7803-0a81e8b09a82           AT        rural
14  fe54f360-db27-0133-c444-0a81e8b09a82           AT      Country
15  960b1ce0-db01-0133-528c-0a81e8b09a82           AT         city
16  d7912480-da41-0133-5bc1-0a81e8b09a82           AT        rural
17  d468c670-da40-0133-de39-0a81e8b09a82           AT    Non-Rural
18  76767d10-dd6c-0133-f56d-0a81e8b09a82           AT         city
19  a96ed910-de55-0133-2582-0a81e8b09a82           AT        rural

In [15]:
pd.read_sql_query("SELECT * from career_info LIMIT 20",engine)

,uuid,dem_education_level,dem_full_time_job,normalized_job_code
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0
2,83127080-da3d-0133-c74f-0a81e8b09a82,None,no,None
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f
5,28583060-dbe2-0133-ff9c-0a81e8b09a82,high,yes,27af8700f5577cec835acee2cb90a2ff
6,b50dbb80-da53-0133-8956-0a81e8b09a82,medium,no,None
7,dd743bb0-d9a5-0133-53b2-0a81e8b09a82,medium,yes,c1b670eba9ccb65e7c99f7da116d5b9c
8,4fde2370-da48-0133-3a42-0a81e8b09a82,medium,yes,d71c4164c99a5f9bca773e755a72f40f
9,9949c4c0-da5f-0133-c832-0a81e8b09a82,no,no,None
10,226cf850-db28-0133-c51a-0a81e8b09a82,high,yes,2ee80cf30e2483dfe0947adc0428f8c5
11,69f1f400-dc5f-0133-ad9b-0a81e8b09a82,medium,no,None
12,2351fbe0-de4c-0133-0d58-0a81e8b09a82,low,yes,897ef18a9321616495831a4b4b0c1bb2
13,0f286c80-dd77-0133-7803-0a81e8b09a82,medium,no,None
14,fe54f360-db27-0133-c444-0a81e8b09a82,medium,no,None
15,960b1ce0-db01-0133-528c-0a81e8b09a82,medium,yes,a003702c0cea282e17967772dd83de5e
16,d7912480-da41-0133-5bc1-0a81e8b09a82,low,no,None
17,d468c670-da40-0133-de39-0a81e8b09a82,high,no,None
18,76767d10-dd6c-0133-f56d-0a81e8b09a82,low,no,None
19,a96ed910-de55-0133-2582-0a81e8b09a82,medium,yes,04c82eae29e1c4a30eac0710b74ab276

In [16]:
pd.read_sql_query("SELECT * from poll_info LIMIT 20",engine)

,uuid,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
5,28583060-dbe2-0133-ff9c-0a81e8b09a82,I understand it fully,I would vote against it,A basic income would not affect my work choices,It encourages financial independence and self-...,It is impossible to finance | It might encoura...
6,b50dbb80-da53-0133-8956-0a81e8b09a82,I know something about it,I would probably vote for it,‰Û_ work as a freelancer,It reduces anxiety about financing basic needs,Foreigners might come to my country and take a...
7,dd743bb0-d9a5-0133-53b2-0a81e8b09a82,I know something about it,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working | Fo...
8,4fde2370-da48-0133-3a42-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It creates more equality of opportunity | It r...,Foreigners might come to my country and take a...
9,9949c4c0-da5f-0133-c832-0a81e8b09a82,I understand it fully,I would vote for it,‰Û_ do more volunteering work,"It increases solidarity, because it is funded ...",Foreigners might come to my country and take a...
10,226cf850-db28-0133-c51a-0a81e8b09a82,I know something about it,I would probably vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,It is against the principle of linking merit a...
11,69f1f400-dc5f-0133-ad9b-0a81e8b09a82,I know something about it,I would probably vote for it,‰Û_ stop working,It increases appreciation for household work a...,Foreigners might come to my country and take a...
12,2351fbe0-de4c-0133-0d58-0a81e8b09a82,I have never heard of it,I would probably vote for it,‰Û_ gain additional skills,It reduces anxiety about financing basic needs...,It might encourage people to stop working | It...
13,0f286c80-dd77-0133-7803-0a81e8b09a82,I have heard just a little about it,I would vote for it,A basic income would not affect my work choices,It creates more equality of opportunity,It might encourage people to stop working | Fo...
14,fe54f360-db27-0133-c444-0a81e8b09a82,I know something about it,I would probably vote for it,‰Û_ gain additional skills,It reduces anxiety about financing basic needs,It might encourage people to stop working | It...
15,960b1ce0-db01-0133-528c-0a81e8b09a82,I know something about it,I would probably vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,It might encourage people to stop working
16,d7912480-da41-0133-5bc1-0a81e8b09a82,I know something about it,I would vote against it,‰Û_ stop working,It encourages financial independence and self-...,Foreigners might come to my country and take a...
17,d468c670-da40-0133-de39-0a81e8b09a82,I know something about it,I would probably vote for it,‰Û_ work as a freelancer,It reduces anxiety about financing basic needs...,It is against the principle of linking merit a...
18,76767d10-dd6c-0133-f56d-0a81e8b09a82,I have never heard of it,I would probably vote against it,‰Û_ gain additional skills,It creates more equality of opportunity,It is impossible to finance | It might encoura...
19,a96ed910-de55-0133-2582-0a81e8b09a82,I have heard just a little about it,I would probably vote against it,None of the above,It reduces anxiety about financing basic needs,It might encourage people to stop working | It...

In [90]:
table_query = """SELECT country_info.country_code, 
career_info.normalized_job_code as uuid, 
personal_info.gender AS 'Gender',
count(country_info.uuid) AS 'Quantity'
FROM country_info
JOIN career_info ON career_info.uuid = country_info.uuid
JOIN personal_info ON personal_info.uuid = country_info.uuid
GROUP BY country_info.country_code"""

main_table = pd.read_sql_query(table_query,engine)

main_table.head()

  country_code                              uuid  Gender  Quantity
0           AT                              None    male       133
1           BE                              None  female       179
2           BG                              None    male       141
3           CY                              None    Male        13
4           CZ  e55556364d2096578fd153e9800e826f    male       189

In [91]:
main_table.shape

(28, 4)

In [92]:
main_table.country_code.unique()

array(['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR',
       'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL',
       'PL', 'PT', 'RO', 'SE', 'SI', 'SK'], dtype=object)

In [98]:
main_table.uuid.unique()

array([None, 'e55556364d2096578fd153e9800e826f',
       'd4624ed8068d24948e18303212593cd6',
       '7028f15ad274cb4d9505101b9c1306b1',
       '679fb7003e0aedc14891fcd15dd846c5',
       'edc64316da9707432443c7a4461abe6c',
       'ec3d88b2fd083b870b8c5a603898ed39',
       '8fd068c8d9be73abfa678856177b6c40',
       '1a281bf4bd1fe9b2a6e464e508bea167',
       '569da68cdcac43a3b4a0126ea9170570',
       'a2a9fbe67b4aa2b551ba0f3adac90a99',
       '27af8700f5577cec835acee2cb90a2ff',
       '07b7555fa790debaf5b04d1409ad5f11',
       '049a3f3a2b5f85cb2971ba77ad66e10c',
       '7bb15eefb19ed09c59349baad7e8469e',
       '7932d4705d002b47789c11edfaed685e',
       '41b2978a2c07c5f477e60f26372d6c85',
       '477b53ef09d37f098d5ed74f47fcbaec',
       'a4d5b8b38f9513825d0d94a981ebe962',
       '499f9d9b6722342608656559b15abd90',
       '775190277a849cba701b306a7b374c0a'], dtype=object)

In [99]:
main_table.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [100]:
main_table['Gender'].str.lower()

main_table.loc[(main_table['Gender'].str.lower().str[0] == 'm'),'Gender']='Male'
main_table.loc[(main_table['Gender'].str.lower().str[0] == 'f'),'Gender']='Female'

In [101]:
main_table.head()

  country_code                              uuid  Gender  Quantity
0           AT                              None    Male       133
1           BE                              None  Female       179
2           BG                              None    Male       141
3           CY                              None    Male        13
4           CZ  e55556364d2096578fd153e9800e826f    Male       189

In [102]:
main_table.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [103]:
main_table

   country_code                              uuid  Gender  Quantity
0            AT                              None    Male       133
1            BE                              None  Female       179
2            BG                              None    Male       141
3            CY                              None    Male        13
4            CZ  e55556364d2096578fd153e9800e826f    Male       189
5            DE  d4624ed8068d24948e18303212593cd6    Male      1420
6            DK                              None  Female       119
7            EE                              None    Male        18
8            ES  7028f15ad274cb4d9505101b9c1306b1    Male      1005
9            FI  679fb7003e0aedc14891fcd15dd846c5    Male       113
10           FR                              None    Male      1248
11           GB  edc64316da9707432443c7a4461abe6c    Male      1199
12           GR  ec3d88b2fd083b870b8c5a603898ed39  Female       225
13           HR  8fd068c8d9be73abfa678856177b6c40    Male        87
14           HU  1a281bf4bd1fe9b2a6e464e508bea167    Male       206
15           IE  569da68cdcac43a3b4a0126ea9170570  Female        90
16           IT  a2a9fbe67b4aa2b551ba0f3adac90a99  Female      1138
17           LT  27af8700f5577cec835acee2cb90a2ff  Female        50
18           LU  07b7555fa790debaf5b04d1409ad5f11  Female        11
19           LV  049a3f3a2b5f85cb2971ba77ad66e10c    Male        36
20           MT  7bb15eefb19ed09c59349baad7e8469e    Male         8
21           NL  7932d4705d002b47789c11edfaed685e    Male       331
22           PL  41b2978a2c07c5f477e60f26372d6c85    Male       860
23           PT  679fb7003e0aedc14891fcd15dd846c5  Female       202
24           RO  477b53ef09d37f098d5ed74f47fcbaec    Male       332
25           SE  a4d5b8b38f9513825d0d94a981ebe962  Female       175
26           SI  499f9d9b6722342608656559b15abd90    Male        28
27           SK  775190277a849cba701b306a7b374c0a    Male        93

In [4]:
import json
import requests
 
response = requests.get('http://api.dataatwork.org/v1/jobs')
results = response.json()
results

[{'uuid': '26bc4486dfd0f60b3bb0d8d64e001800',
  'title': '1st Grade Teacher',
  'normalized_job_title': '1st grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': '9be6e14491305132c175cb1781a3356c',
  'title': '1st Pressman',
  'normalized_job_title': '1st pressman',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': 'd38d16bab3f9f25ae34ae3e2aad254d4',
  'title': '1st Pressman On Web Press',
  'normalized_job_title': '1st pressman on web press',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': '8576a78b5c1cae3a567ca7fd34500357',
  'title': '21 Dealer',
  'normalized_job_title': '21 dealer',
  'parent_uuid': '4be080220c824dcb435d59ebf1c3ce80'},
 {'uuid': 'a59278d7f653db37e54a270345a91a05',
  'title': '2nd Grade Teacher',
  'normalized_job_title': '2nd grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': '9c631442c4966cd3e5a9e52fc70aff1c',
  'title': '2nd Pressman',
  'normalized_job_title': '2nd pressman',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': 'f5a2151d370ebca7b49778e036a287e8',
  'title': '2 Year Olds Preschool Teacher',
  'normalized_job_title': '2 year olds preschool teacher',
  'parent_uuid': 'd78b3ba8b749686d739480ee77f9e219'},
 {'uuid': 'af2e31c2c64ae223b06eb7f0cbf59a98',
  'title': '3D Animator',
  'normalized_job_title': '3d animator',
  'parent_uuid': 'caa551520f21c7c220716a8f82806246'},
 {'uuid': 'ac029293b0ea43f168b004c4f04fca31',
  'title': '3D Artist',
  'normalized_job_title': '3d artist',
  'parent_uuid': 'caa551520f21c7c220716a8f82806246'},
 {'uuid': '7d37dfe2eface4ae79db093b0a79385d',
  'title': '3D Designer',
  'normalized_job_title': '3d designer',
  'parent_uuid': 'caa551520f21c7c220716a8f82806246'},
 {'uuid': '6cb0a6786c08d6c91a4fc9f61e19f62d',
  'title': '3D Modeler',
  'normalized_job_title': '3d modeler',
  'parent_uuid': 'caa551520f21c7c220716a8f82806246'},
 {'uuid': 'ec45194ae348e1bb21415064364f038b',
  'title': '3D Specialist',
  'normalized_job_title': '3d specialist',
  'parent_uuid': 'caa551520f21c7c220716a8f82806246'},
 {'uuid': '4266e89fcaf06973fa23fc6f75b27682',
  'title': '3D Technologist',
  'normalized_job_title': '3d technologist',
  'parent_uuid': 'ce1c0fc273d3c803e94a73ff0b54816e'},
 {'uuid': '0cfb09fa1c6691fd6d77a3d3743fa8bc',
  'title': '3rd Grade Reading Teacher',
  'normalized_job_title': '3rd grade reading teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': 'ac668f6dc8795ace795b2c1f7c889ba4',
  'title': '3rd Grade Teacher',
  'normalized_job_title': '3rd grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': '7826ba3a7150817935915f63b861936b',
  'title': '3rd Pressman',
  'normalized_job_title': '3rd pressman',
  'parent_uuid': '96f1cf15fe5880d8660c70f0756944ab'},
 {'uuid': '90bc1d89aaee33a96c1b70fef0750d62',
  'title': '411 Directory Assistance Operator',
  'normalized_job_title': '411 directory assistance operator',
  'parent_uuid': 'f0fc66d367f370fa64da4780019702cd'},
 {'uuid': '814eb6844cf824e6945fb02a48f0e569',
  'title': '4-H Youth Development Specialist',
  'normalized_job_title': '4h youth development specialist',
  'parent_uuid': '1028b80a2ce2bfb940b2198f487c6abb'},
 {'uuid': '772053d8bb2c6e127b0bf216e50285ed',
  'title': '4th Grade Math Teacher',
  'normalized_job_title': '4th grade math teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'uuid': 'de0a3e90cdd112dd78120d4c8a9422b2',
  'title': '4th Grade Teacher',
  'normalized_job_title': '4th grade teacher',
  'parent_uuid': '51cc95467c1844c7dc1d923265c023b2'},
 {'links': [{'rel': 'self', 'href': '/jobs?offset=0&limit=20'},
   {'rel': 'first', 'href': '/jobs?offset=0&limit=20'},
   {'rel': 'next', 'href': '/jobs?offset=20&limit=20'},
   {'rel': 'last', 'href': '/jobs?offset=46260&limit=20'}]}]

In [5]:
jobs = pd.DataFrame(results)
jobs

,uuid,title,normalized_job_title,parent_uuid,links
0,26bc4486dfd0f60b3bb0d8d64e001800,1st Grade Teacher,1st grade teacher,51cc95467c1844c7dc1d923265c023b2,NaN
1,9be6e14491305132c175cb1781a3356c,1st Pressman,1st pressman,96f1cf15fe5880d8660c70f0756944ab,NaN
2,d38d16bab3f9f25ae34ae3e2aad254d4,1st Pressman On Web Press,1st pressman on web press,96f1cf15fe5880d8660c70f0756944ab,NaN
3,8576a78b5c1cae3a567ca7fd34500357,21 Dealer,21 dealer,4be080220c824dcb435d59ebf1c3ce80,NaN
4,a59278d7f653db37e54a270345a91a05,2nd Grade Teacher,2nd grade teacher,51cc95467c1844c7dc1d923265c023b2,NaN
5,9c631442c4966cd3e5a9e52fc70aff1c,2nd Pressman,2nd pressman,96f1cf15fe5880d8660c70f0756944ab,NaN
6,f5a2151d370ebca7b49778e036a287e8,2 Year Olds Preschool Teacher,2 year olds preschool teacher,d78b3ba8b749686d739480ee77f9e219,NaN
7,af2e31c2c64ae223b06eb7f0cbf59a98,3D Animator,3d animator,caa551520f21c7c220716a8f82806246,NaN
8,ac029293b0ea43f168b004c4f04fca31,3D Artist,3d artist,caa551520f21c7c220716a8f82806246,NaN
9,7d37dfe2eface4ae79db093b0a79385d,3D Designer,3d designer,caa551520f21c7c220716a8f82806246,NaN
10,6cb0a6786c08d6c91a4fc9f61e19f62d,3D Modeler,3d modeler,caa551520f21c7c220716a8f82806246,NaN
11,ec45194ae348e1bb21415064364f038b,3D Specialist,3d specialist,caa551520f21c7c220716a8f82806246,NaN
12,4266e89fcaf06973fa23fc6f75b27682,3D Technologist,3d technologist,ce1c0fc273d3c803e94a73ff0b54816e,NaN
13,0cfb09fa1c6691fd6d77a3d3743fa8bc,3rd Grade Reading Teacher,3rd grade reading teacher,51cc95467c1844c7dc1d923265c023b2,NaN
14,ac668f6dc8795ace795b2c1f7c889ba4,3rd Grade Teacher,3rd grade teacher,51cc95467c1844c7dc1d923265c023b2,NaN
15,7826ba3a7150817935915f63b861936b,3rd Pressman,3rd pressman,96f1cf15fe5880d8660c70f0756944ab,NaN
16,90bc1d89aaee33a96c1b70fef0750d62,411 Directory Assistance Operator,411 directory assistance operator,f0fc66d367f370fa64da4780019702cd,NaN
17,814eb6844cf824e6945fb02a48f0e569,4-H Youth Development Specialist,4h youth development specialist,1028b80a2ce2bfb940b2198f487c6abb,NaN
18,772053d8bb2c6e127b0bf216e50285ed,4th Grade Math Teacher,4th grade math teacher,51cc95467c1844c7dc1d923265c023b2,NaN
19,de0a3e90cdd112dd78120d4c8a9422b2,4th Grade Teacher,4th grade teacher,51cc95467c1844c7dc1d923265c023b2,NaN
20,NaN,NaN,NaN,NaN,"[{'rel': 'self', 'href': '/jobs?offset=0&limit..."

In [6]:
clean_jobs = jobs[['uuid','title']]
clean_jobs

                                uuid                              title
0   26bc4486dfd0f60b3bb0d8d64e001800                  1st Grade Teacher
1   9be6e14491305132c175cb1781a3356c                       1st Pressman
2   d38d16bab3f9f25ae34ae3e2aad254d4          1st Pressman On Web Press
3   8576a78b5c1cae3a567ca7fd34500357                          21 Dealer
4   a59278d7f653db37e54a270345a91a05                  2nd Grade Teacher
5   9c631442c4966cd3e5a9e52fc70aff1c                       2nd Pressman
6   f5a2151d370ebca7b49778e036a287e8      2 Year Olds Preschool Teacher
7   af2e31c2c64ae223b06eb7f0cbf59a98                        3D Animator
8   ac029293b0ea43f168b004c4f04fca31                          3D Artist
9   7d37dfe2eface4ae79db093b0a79385d                        3D Designer
10  6cb0a6786c08d6c91a4fc9f61e19f62d                         3D Modeler
11  ec45194ae348e1bb21415064364f038b                      3D Specialist
12  4266e89fcaf06973fa23fc6f75b27682                    3D Technologist
13  0cfb09fa1c6691fd6d77a3d3743fa8bc          3rd Grade Reading Teacher
14  ac668f6dc8795ace795b2c1f7c889ba4                  3rd Grade Teacher
15  7826ba3a7150817935915f63b861936b                       3rd Pressman
16  90bc1d89aaee33a96c1b70fef0750d62  411 Directory Assistance Operator
17  814eb6844cf824e6945fb02a48f0e569   4-H Youth Development Specialist
18  772053d8bb2c6e127b0bf216e50285ed             4th Grade Math Teacher
19  de0a3e90cdd112dd78120d4c8a9422b2                  4th Grade Teacher
20                               NaN                                NaN

In [110]:
final = pd.merge(main_table, clean_jobs, on="uuid")
final

  country_code  uuid  Gender  Quantity title
0           AT  None    Male       133   NaN
1           BE  None  Female       179   NaN
2           BG  None    Male       141   NaN
3           CY  None    Male        13   NaN
4           DK  None  Female       119   NaN
5           EE  None    Male        18   NaN
6           FR  None    Male      1248   NaN

In [83]:
table_query2 = """SELECT *
FROM country_info
JOIN career_info ON career_info.uuid = country_info.uuid
JOIN personal_info ON personal_info.uuid = country_info.uuid
GROUP BY country_info.country_code"""

main_table2 = pd.read_sql_query(table_query2,engine)
main_table2.rename(columns={'normalized_job_code': 'parent_uuid'},inplace=True)

main_table2.head()

,uuid,country_code,rural,uuid,dem_education_level,dem_full_time_job,parent_uuid,uuid,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,dcab3aa0-dc79-0133-412b-0a81e8b09a82,BE,urban,dcab3aa0-dc79-0133-412b-0a81e8b09a82,medium,no,None,dcab3aa0-dc79-0133-412b-0a81e8b09a82,48 years old,female,yES,40_65
2,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,BG,Non-Rural,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,medium,no,None,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,40 years old,male,nO,40_65
3,4b218c60-d966-0133-f927-0a81e8b09a82,CY,city,4b218c60-d966-0133-f927-0a81e8b09a82,low,no,None,4b218c60-d966-0133-f927-0a81e8b09a82,2000,Male,nO,juvenile
4,69ebc3b0-d989-0133-9cad-0a81e8b09a82,CZ,city,69ebc3b0-d989-0133-9cad-0a81e8b09a82,medium,yes,e55556364d2096578fd153e9800e826f,69ebc3b0-d989-0133-9cad-0a81e8b09a82,1986,male,nO,26_39

In [85]:
final2 = pd.merge(main_table2, clean_jobs, on="uuid")
final2

,uuid,country_code,rural,uuid,dem_education_level,dem_full_time_job,parent_uuid,uuid,age,gender,dem_has_children,age_group,title
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,None,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,NaN
1,dcab3aa0-dc79-0133-412b-0a81e8b09a82,BE,urban,dcab3aa0-dc79-0133-412b-0a81e8b09a82,medium,no,None,dcab3aa0-dc79-0133-412b-0a81e8b09a82,48 years old,female,yES,40_65,NaN
2,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,BG,Non-Rural,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,medium,no,None,c5133fb0-dad4-0133-3b1b-0a81e8b09a82,40 years old,male,nO,40_65,NaN
3,4b218c60-d966-0133-f927-0a81e8b09a82,CY,city,4b218c60-d966-0133-f927-0a81e8b09a82,low,no,None,4b218c60-d966-0133-f927-0a81e8b09a82,2000,Male,nO,juvenile,NaN
4,a40a1b10-d949-0133-1a32-0a81e8b09a82,DK,city,a40a1b10-d949-0133-1a32-0a81e8b09a82,medium,no,None,a40a1b10-d949-0133-1a32-0a81e8b09a82,47 years old,Fem,nO,40_65,NaN
5,eb9d36d0-d969-0133-7a47-0a81e8b09a82,EE,urban,eb9d36d0-d969-0133-7a47-0a81e8b09a82,low,no,None,eb9d36d0-d969-0133-7a47-0a81e8b09a82,1999,male,nO,14_25,NaN
6,fdc6dff0-da94-0133-37fc-0a81e8b09a82,FR,rural,fdc6dff0-da94-0133-37fc-0a81e8b09a82,medium,no,None,fdc6dff0-da94-0133-37fc-0a81e8b09a82,49 years old,male,YES,40_65,NaN

In [84]:
def get_database():
    """
    Function to connect to the database.
    The file must be called raw_data_project_m1.db and has to be in the data folder.
    """
    print('connecting to the database...')
    db_path = '../data/raw_data_project_m1.db'
    conn_str = f'sqlite:///{db_path}'
    engine = create_engine(conn_str)
    table_names = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)
    tables_names_lst = table_names['name'].to_list()
    all_dfs = [pd.read_sql_query(f'select * from {i}', engine) for i in tables_names_lst]
    merged_tables = reduce(lambda left, right: pd.merge(left, right, on='uuid'), all_dfs)
    print('connected!')
    return merged_tables

full_df = get_database()
full_df

connecting to the database...
connected!

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65,AT,countryside,no,no,None,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39,AT,city,None,no,None,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,AT,Country,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65,AT,city,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,FeMale,nO,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,male,NO,juvenile,SK,Non-Rural,low,no,None,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,male,yES,40_65,SK,city,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,FeMale,YES,40_65,SK,city,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [162]:
def job_ids(merged_tables):
    jobs_ids = list(merged_tables['normalized_job_code'].unique())
    print('Import finsihed :)')
    return jobs_ids

def get_job(jobs_id):
    print('Calling the api...')
    jobs_list = []
    for id in jobs_id:
        if id == None:
            pass
        else:
            api_url = requests.get(f'http://api.dataatwork.org/v1/jobs/{id}')
            json_data = api_url.json()
            jobs_list.append(json_data)
    jobs_df_raw = pd.DataFrame(jobs_list)
    jobs_df = jobs_df_raw.rename(columns={'uuid': "normalized_job_code"})
    print('API connection completed!')
    return jobs_df


jobs = job_ids(full_df)
jobs_defined = get_job(jobs)
jobs_defined

Import finsihed :)
Calling the api...
API connection completed!

,normalized_job_code,title,normalized_job_title,parent_uuid
0,861a9b9151e11362eb3c77ca914172d0,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056
1,049a3f3a2b5f85cb2971ba77ad66e10c,Data Coordinator,data coordinator,0b9dd32a367f4562ec77b993053d1910
2,f4b2fb1aa40f661488e2782b6d57ad2f,Database Developer,database developer,b90ca4df5690002377a7b0f1f3d40781
3,27af8700f5577cec835acee2cb90a2ff,Data Entry Specialist,data entry specialist,bf88358c56bb6cbe7eabec38ae333d19
4,c1b670eba9ccb65e7c99f7da116d5b9c,Database Architect,database architect,596226d5f9ef63de41a852826d483d19
...,...,...,...,...
151,b0fa6ede410f50b82ab74f5a705fe699,Analytical Data Miner,analytical data miner,9656fa2dc39e9643c00a45858e0117d0
152,559a21f836c93876f31b60e6d10656a7,Data Analysis Assistant,data analysis assistant,325e2251e20170928426473156bd3c48
153,c1fb1a01b78373ac2153c66fa08d16dc,Data Examination Clerk,data examination clerk,da412504dd7b130414b7bbfa2acd563b
154,05bb9a333a66d6eb151e253623efe1c0,Data Entry Clerk,data entry clerk,bf88358c56bb6cbe7eabec38ae333d19
155,4cee16550636e292b8d136486fce943b,Data Capture Clerk,data capture clerk,bf88358c56bb6cbe7eabec38ae333d19

In [ ]:
url = 'https://datatau.net'
html = requests.get(url).content
html[:5000]

In [19]:
url = 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes'
html = requests.get(url).content
html[:5000]

b'\xef\xbb\xbf<!DOCTYPE html>\n<html lang="en" dir="ltr" class="client-nojs">\n<head>\n<meta http-equiv="X-UA-Compatible" content="Ie=Edge,chrome=1"/> <meta charset="UTF-8" /><title>Glossary:Country codes - Statistics Explained</title>\n<meta name="generator" content="MediaWiki 1.22.5" />\n<link rel="shortcut icon" href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" />\n<link rel="search" type="application/opensearchdescription+xml" href="/eurostat/statistics-explained/opensearch_desc.php" title="Statistics Explained (en)" />\n<link rel="EditURI" type="application/rsd+xml" href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" />\n<link rel="alternate" type="application/atom+xml" title="Statistics Explained Atom feed" href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<meta name="ResourceLoaderDynamicStyles" content="" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>\n\n<script src="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=statexpflat&amp;*"></script>\n<script>if(window.mw){\nmw.config.set( {\n    "wgCanonicalNamespace": "Glossary",\n    "wgCanonicalSpecialPageName": false,\n    "wgNamespaceNumber": 100,\n    "wgPageName": "Glossary:Country_codes",\n    "wgTitle": "Country codes",\n    "wgCurRevisionId": 512615,\n    "wgRevisionId": 512615,\n    "wgArticleId": 1994,\n    "wgIsArticle": true,\n    "wgIsRedirect": false,\n    "wgAction": "view",\n    "wgUserName": null,\n    "wgUserGroups": [\n        "*"\n    ],\n    "wgCategories": [\n        "Geography glossary",\n        "Glossary"\n    ],\n    "wgBreakFrames": false,\n    "wgPageContentLanguage": "en",\n    "wgPageContentModel": "wikitext",\n    "wgSeparatorTransformTable": [\n        "",\n        ""\n    ],\n    "wgDigitTransformTable": [\n        "",\n        ""\n    ],\n    "wgDefaultDateFormat": "dmy",\n    "wgMonthNames": [\n        "",\n        "January",\n        "February",\n        "March",\n        "April",\n        "May",\n        "June",\n        "July",\n        "August",\n        "September",\n        "October",\n        "November",\n        "December"\n    ],\n    "wgMonthNamesShort": [\n        "",\n        "Jan",\n        "Feb",\n        "Mar",\n        "Apr",\n        "May",\n        "Jun",\n        "Jul",\n        "Aug",\n        "Sep",\n        "Oct",\n        "Nov",\n        "Dec"\n    ],\n    "wgRelevantPageName": "Glossary:Country_codes",\n    "wgIsProbablyEditable": false,\n    "wgRestrictionEdit": [],\n    "wgRestrictionMove": [],\n    "wgWikiEditorEnabledModules": {\n        "toolbar": true,\n        "dialogs": false,\n        "hidesig": true,\n        "templateEditor": false,\n        "templates": false,\n        "preview": false,\n        "previewDialog": false,\n        "publish": false,\n        "toc": false\n    },\n    "wgCategoryTreePageCategoryOptions": "{\\"mode\\":0,\\"hideprefix\\":20,\\"showcount\\":true,\\"namespaces\\":false}"\n} );\n}</script><script>if(window.mw){\nmw.loader.implement( "user.options", function () {\nmw.user.options.set( {\n    "ccmeonemails": 0,\n    "cols": 80,\n    "date": "default",\n    "diffonly": 0,\n    "disablemail": 0,\n    "disablesuggest": 0,\n    "editfont": "default",\n    "editondblclick": 0,\n    "editsection": 1,\n    "editsectiononrightclick": 0,\n    "enotifminoredits": 0,\n    "enotifrevealaddr": 0,\n    "enotifusertalkpages": 1,\n    "enotifwatchlistpages": 1,\n    "extendwatchlist": 0,\n    "fancysig": 0,\n    "forceeditsummary": 0,\n    "gender": "unknown",\n    "hideminor": 0,\n    "hidepatrolled": 0,\n    "imagesize": 2,\n    "justify": 0,\n    "math": 6,\n    "minordefault": 0,\n    "newpageshidepatrolled": 0,\n    "nocache": 0,\n    "noconvertlink": 0,\n    "norollbackdiff": 0,\n    "numberheadings": 0,\n    "previewonfirst": 0,\n    "previewontop": 1,\n    "rcdays": 7,\n    "rclimit": 50,\n    "rememberpassword": 0,\n    "rows": 25,\n    "searchlimit": 20,\n    "showhiddencats": 0,\n    "shownumberswatching": 1,\n    "showtoc": 1,\n    "showtoolbar": 1,\n   '

In [20]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')

soup

<!DOCTYPE html>

<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta content="Ie=Edge,chrome=1" http-equiv="X-UA-Compatible"/> <meta charset="utf-8"/><title>Glossary:Country codes - Statistics Explained</title>
<meta content="MediaWiki 1.22.5" name="generator"/>
<link href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" rel="shortcut icon"/>
<link href="/eurostat/statistics-explained/opensearch_desc.php" rel="search" title="Statistics Explained (en)" type="application/opensearchdescription+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Statistics Explained Atom feed" type="application/atom+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>
<script src="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=statexpflat&amp;*"></script>
<script>if(window.mw){
mw.config.set( {
    "wgCanonicalNamespace": "Glossary",
    "wgCanonicalSpecialPageName": false,
    "wgNamespaceNumber": 100,
    "wgPageName": "Glossary:Country_codes",
    "wgTitle": "Country codes",
    "wgCurRevisionId": 512615,
    "wgRevisionId": 512615,
    "wgArticleId": 1994,
    "wgIsArticle": true,
    "wgIsRedirect": false,
    "wgAction": "view",
    "wgUserName": null,
    "wgUserGroups": [
        "*"
    ],
    "wgCategories": [
        "Geography glossary",
        "Glossary"
    ],
    "wgBreakFrames": false,
    "wgPageContentLanguage": "en",
    "wgPageContentModel": "wikitext",
    "wgSeparatorTransformTable": [
        "",
        ""
    ],
    "wgDigitTransformTable": [
        "",
        ""
    ],
    "wgDefaultDateFormat": "dmy",
    "wgMonthNames": [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "wgMonthNamesShort": [
        "",
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
    ],
    "wgRelevantPageName": "Glossary:Country_codes",
    "wgIsProbablyEditable": false,
    "wgRestrictionEdit": [],
    "wgRestrictionMove": [],
    "wgWikiEditorEnabledModules": {
        "toolbar": true,
        "dialogs": false,
        "hidesig": true,
        "templateEditor": false,
        "templates": false,
        "preview": false,
        "previewDialog": false,
        "publish": false,
        "toc": false
    },
    "wgCategoryTreePageCategoryOptions": "{\"mode\":0,\"hideprefix\":20,\"showcount\":true,\"namespaces\":false}"
} );
}</script><script>if(window.mw){
mw.loader.implement( "user.options", function () {
mw.user.options.set( {
    "ccmeonemails": 0,
    "cols": 80,
    "date": "default",
    "diffonly": 0,
    "disablemail": 0,
    "disablesuggest": 0,
    "editfont": "default",
    "editondblclick": 0,
    "editsection": 1,
    "editsectiononrightclick": 0,
    "enotifminoredits": 0,
    "enotifrevealaddr": 0,
    "enotifusertalkpages": 1,
    "enotifwatchlistpages": 1,
    "extendwatchlist": 0,
    "fancysig": 0,
    "forceeditsummary": 0,
    "gender": "unknown",
    "hideminor": 0,
    "hidepatrolled": 0,
    "imagesize": 2,
    "justify": 0,
    "math": 6,
    "minordefault": 0,
    "newpageshidepatrolled": 0,
    "nocache": 0,
    "noconvertlink": 0,
    "norollbackdiff": 0,
    "numberheadings": 0,
    "previewonfirst": 0,
    "previewontop": 1,
    "rcdays": 7,
    "rclimit": 50,
    "rememberpassword": 0,
    "rows": 25,
    "searchlimit": 20,
    "showhiddencats": 0,
    "shownumberswatching": 1,
    "showtoc": 1,
    "showtoolbar": 1,
    "skin": "statexpflat",
    "stubthreshold": 0,
    "thumbsize": 2,
    "underline": 2,
    "uselivepreview": 0,
    "usenewrc": 0,
    "vector-simplesearch": 1,
    "watchcreations": 0,
    "watchdefault": 0,
    "watchdeletion": 0,
    "watchlistdays": 3,
    "watchlisthideanons": 0,
    "watchlisthidebots": 0,
    "watchlisthideliu": 0,
    "watchlisthideminor": 0,
    "watchlisthideown": 0,
    "watchlisthidepatrolled": 0,
    "watchmoves": 0,
    "wllimit": 250,
    "useeditwarning": 1,
    "prefershttps": 1,
    "flaggedrevsstable": 1,
    "usebetatoolbar": 1,
    "mathJax": true,
    "language": "en",
    "variant-gan": "gan",
    "variant-iu": "iu",
    "variant-kk": "kk",
    "variant-ku": "ku",
    "variant-shi": "shi",
    "variant-sr": "sr",
    "variant-tg": "tg",
    "variant-uz": "uz",
    "variant-zh": "zh",
    "searchNs0": true,
    "searchNs1": false,
    "searchNs2": false,
    "searchNs3": false,
    "searchNs4": false,
    "searchNs5": false,
    "searchNs6": false,
    "searchNs7": false,
    "searchNs8": false,
    "searchNs9": false,
    "searchNs10": false,
    "searchNs11": false,
    "searchNs12": false,
    "searchNs13": false,
    "searchNs14": false,
    "searchNs15": false,
    "searchNs100": false,
    "searchNs101": false,
    "searchNs104": false,
    "searchNs105": false,
    "searchNs108": false,
    "searchNs110": false,
    "searchNs111": false,
    "searchNs112": false,
    "searchNs113": false,
    "searchNs114": false,
    "searchNs120": false,
    "searchNs121": false,
    "searchNs122": false,
    "searchNs123": false,
    "searchNs124": false,
    "searchNs125": false,
    "searchNs126": false,
    "searchNs127": false,
    "searchNs128": false,
    "searchNs129": false,
    "searchNs130": false,
    "searchNs131": false,
    "searchNs132": false,
    "searchNs133": false,
    "searchNs134": false,
    "searchNs135": false,
    "searchNs154": false,
    "searchNs155": false,
    "variant": "en"
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.implement( "user.tokens", function () {
mw.user.tokens.set( {
    "editToken": "+\\",
    "patrolToken": false,
    "watchToken": false
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
<link href="/eurostat/statistics-explained/extensions/EditWarning/style.css" rel="stylesheet" type="text/css"/>
<script src="/eurostat/statistics-explained/extensions/StatexpVislet/StatexpVislet.js"></script><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat-grid.css" rel="stylesheet"/>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/modernizr.custom.36138.js"></script>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/css3-mediaqueries.js"></script><!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/html5shiv.min.js"></script>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/respond.min.js"></script>
			<![endif]--></head>
<body class="mediawiki ltr sitedir-ltr ns-100 ns-subject page-Glossary_Country_codes skin-statexpflat action-view">
<!--

                <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

-->
<div class="container">
<div class="header" id="se-header">
<div class="grey-stripe"></div>
<div class="flag hidden-xs hidden-sm"></div>
<div class="flag-mobile hidden-md hidden-lg"></div>
<ul class="login list-inline hidden-xs hidden-sm">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li><a accesskey="o" href="/eurostat/statistics-explained/index.php?title=Special:UserLogin&amp;returnto=Glossary%3ACountry+codes" title="Login is required to edit (reserved for Eurostat and accredited contributors)">log in</a></li>
<li class="login-icon"></li>
</ul>
<div class="heading">
<!--<div class="statexp-small hidden-lg hidden-md">Statistics Explained</div>-->
<div class="lighthouse articles visible-lg-block"></div>
<div class="alert alert-th3" style="

       position: absolute;
    z-index: 150;
    width: 300px;
    top: 60px;
    margin-left: 200px;
    background-color: #FF7900;
    color: #f9f9f9;
    font-weight: bolder;
    font-size: 12px;

"><p>Try the new automatic translation by clicking on the blue icon “Translate” up in the right corner of the article!</p></div>
<div class="links hidden-xs hidden-sm">
<ul class="list-inline">
<li class="lang-selector hidden-xs hidden-sm">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" id="lang-selector" type="button">
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes">English</a> <span class="caret"></span>
</button>
<ul aria-labelledby="dLabel" class="dropdown-menu" role="menu">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/de">Deutsch</a></li>
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/fr">français</a></li>
</ul>
</div>
</li>
</ul>
</div>
<!----
		<div class="eurostat">eurostat</div>
		<div class="statexp">Statistics Explained</div>
		<!---->
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page"><div class="statexptitle"></div></a>
<div class="mobile-header-buttons hidden-md hidden-lg">
<button class="bt-open" id="mobile-menu-button">
<span class="glyphicon glyphicon-align-justify icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
<button class="bt-open" id="mobile-search-button">
<span class="glyphicon glyphicon-search icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
</div>
<!-- -->
<div class="search-box hidden-xs hidden-sm">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="row hidden-xs hidden-sm">
<div class="col-lg-12" id="menu-bar-container">
<div class="row menu-bar-container">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row hidden-md hidden-lg">
<div class="col-sm-12 col-xs-12 mobile-search">
<div class="search-box search-box-mobile hidden-md hidden-lg">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="col-sm-12 col-xs-12 mobile-menu">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
<!--END HEADER BEGIN PAGE-->
<!----
<div class="onerow">
<!---->
<div class="row content-row">
<!-- BEGIN LSF -->
<!-- -->
<div class="hidden-md hidden-lg hidden-xs hidden-sm sidebar content-col">
<!----
		<div class="col2 sidebar">
		<!---->
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>

In [56]:
countries_list = soup.find_all('td')
countries_list

[<td>Belgium
 </td>,
 <td>(BE)
 </td>,
 <td>Greece
 </td>,
 <td>(EL)
 </td>,
 <td>Lithuania
 </td>,
 <td>(LT)
 </td>,
 <td>Portugal
 </td>,
 <td>(PT)
 </td>,
 <td>Bulgaria
 </td>,
 <td>(BG)
 </td>,
 <td>Spain
 </td>,
 <td>(ES)
 </td>,
 <td>Luxembourg
 </td>,
 <td>(LU)
 </td>,
 <td>Romania
 </td>,
 <td>(RO)
 </td>,
 <td>Czechia
 </td>,
 <td>(CZ)
 </td>,
 <td>France
 </td>,
 <td>(FR)
 </td>,
 <td>Hungary
 </td>,
 <td>(HU)
 </td>,
 <td>Slovenia
 </td>,
 <td>(SI)
 </td>,
 <td>Denmark
 </td>,
 <td>(DK)
 </td>,
 <td>Croatia
 </td>,
 <td>(HR)
 </td>,
 <td>Malta
 </td>,
 <td>(MT)
 </td>,
 <td>Slovakia
 </td>,
 <td>(SK)
 </td>,
 <td>Germany
 </td>,
 <td>(DE)
 </td>,
 <td>Italy
 </td>,
 <td>(IT)
 </td>,
 <td>Netherlands
 </td>,
 <td>(NL)
 </td>,
 <td>Finland
 </td>,
 <td>(FI)
 </td>,
 <td>Estonia
 </td>,
 <td>(EE)
 </td>,
 <td>Cyprus
 </td>,
 <td>(CY)
 </td>,
 <td>Austria
 </td>,
 <td>(AT)
 </td>,
 <td>Sweden
 </td>,
 <td>(SE)
 </td>,
 <td>Ireland
 </td>,
 <td>(IE)
 </td>,
 <td>Latvia
 </td>,
 <td>(LV)
 </td>,
 <td>Poland
 </td>,
 <td>(PL)
 </td>,
 <td> Iceland
 </td>,
 <td> (IS)
 </td>,
 <td>
 </td>,
 <td> Norway
 </td>,
 <td> (NO)
 </td>,
 <td> Liechtenstein
 </td>,
 <td> (LI)
 </td>,
 <td>
 </td>,
 <td> Switzerland
 </td>,
 <td> (CH)
 </td>,
 <td> United Kingdom
 </td>,
 <td> (UK)
 </td>,
 <td>
 </td>,
 <td> Montenegro
 </td>,
 <td> (ME)
 </td>,
 <td> North Macedonia
 </td>,
 <td> (MK)
 </td>,
 <td> Albania
 </td>,
 <td> (AL)
 </td>,
 <td>Serbia
 </td>,
 <td> (RS)
 </td>,
 <td> Turkey
 </td>,
 <td> (TR)
 </td>,
 <td> Bosnia and Herzegovina
 </td>,
 <td> (BA)
 </td>,
 <td> Kosovo*
 </td>,
 <td> (XK<sup class="reference" id="cite_ref-1"><a href="#cite_note-1">[1]</a></sup>)
 </td>,
 <td> Armenia
 </td>,
 <td> (AM)
 </td>,
 <td>
 </td>,
 <td> Belarus
 </td>,
 <td> (BY)
 </td>,
 <td>
 </td>,
 <td> Georgia
 </td>,
 <td> (GE)
 </td>,
 <td> Azerbaijan
 </td>,
 <td> (AZ)
 </td>,
 <td>
 </td>,
 <td> Moldova
 </td>,
 <td> (MD)
 </td>,
 <td>
 </td>,
 <td> Ukraine
 </td>,
 <td> (UA)
 </td>,
 <td> Algeria
 </td>,
 <td> (DZ)
 </td>,
 <td>
 </td>,
 <td> Lebanon
 </td>,
 <td> (LB)
 </td>,
 <td>
 </td>,
 <td> Syria
 </td>,
 <td> (SY)
 </td>,
 <td> Egypt
 </td>,
 <td> (EG)
 </td>,
 <td>
 </td>,
 <td> Libya
 </td>,
 <td> (LY)
 </td>,
 <td>
 </td>,
 <td> Tunisia
 </td>,
 <td> (TN)
 </td>,
 <td> Israel
 </td>,
 <td> (IL)
 </td>,
 <td>
 </td>,
 <td> Morocco
 </td>,
 <td> (MA)
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td> Jordan
 </td>,
 <td> (JO)
 </td>,
 <td>
 </td>,
 <td> Palestine <sup class="reference" id="cite_ref-2"><a href="#cite_note-2">[2]</a></sup>
 </td>,
 <td> (PS)
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td>
 </td>,
 <td> Russia
 </td>,
 <td> (RU)
 </td>,
 <td>Argentina
 </td>,
 <td>(AR)
 </td>,
 <td>
 </td>,
 <td>China (except Hong Kong)
 </td>,
 <td>(CN_X_HK)
 </td>,
 <td>
 </td>,
 <td>Mexico
 </td>,
 <td>(MX)
 </td>,
 <td>
 </td>,
 <td>South Africa
 </td>,
 <td>(ZA)
 </td>,
 <td>Australia
 </td>,
 <td>(AU)
 </td>,
 <td>
 </td>,
 <td>Hong Kong
 </td>,
 <td>(HK)
 </td>,
 <td>
 </td>,
 <td>Nigeria
 </td>,
 <td>(NG)
 </td>,
 <td>
 </td>,
 <td>South Korea
 </td>,
 <td>(KR)
 </td>,
 <td>Brazil
 </td>,
 <td>(BR)
 </td>,
 <td>
 </td>,
 <td>India
 </td>,
 <td>(IN)
 </td>,
 <td>
 </td>,
 <td>New Zealand
 </td>,
 <td>(NZ)
 </td>,
 <td>
 </td>,
 <td>Taiwan
 </td>,
 <td>(TW)
 </td>,
 <td>Canada
 </td>,
 <td>(CA)
 </td>,
 <td>
 </td>,
 <td>Japan
 </td>,
 <td>(JP)
 </td>,
 <td>
 </td>,
 <td>Singapore
 </td>,
 <td>(SG)
 </td>,
 <td>
 </td>,
 <td>United States
 </td>,
 <td>(US)
 </td>]

In [59]:
all_tables = pd.read_html(url)
len(all_tables)

9

Empty DataFrame
Columns: []
Index: []

In [67]:
pandas_html_join = pd.DataFrame()

for i in range(len(all_tables)):
    new_df = pd.read_html(url)[i]
    pd.concat(pandas_html_join,new_df)
    

pandas_html_join

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [71]:
table_0 = pd.read_html(url)[0]
table_1 = pd.read_html(url)[1]
table_2 = pd.read_html(url)[2]
table_3 = pd.read_html(url)[3]
table_4 = pd.read_html(url)[4]
table_5 = pd.read_html(url)[5]
table_6 = pd.read_html(url)[6]
table_7 = pd.read_html(url)[7]
table_8 = pd.read_html(url)[8]

countries_table = pd.concat([table_0, table_1, table_2, table_3, table_4, table_5, table_6, table_7, table_8])
countries_table

,0,1,2,3,4,5,6,7,8,9,10
0,Belgium,(BE),Greece,(EL),Lithuania,(LT),Portugal,(PT),NaN,NaN,NaN
1,Bulgaria,(BG),Spain,(ES),Luxembourg,(LU),Romania,(RO),NaN,NaN,NaN
2,Czechia,(CZ),France,(FR),Hungary,(HU),Slovenia,(SI),NaN,NaN,NaN
3,Denmark,(DK),Croatia,(HR),Malta,(MT),Slovakia,(SK),NaN,NaN,NaN
4,Germany,(DE),Italy,(IT),Netherlands,(NL),Finland,(FI),NaN,NaN,NaN
5,Estonia,(EE),Cyprus,(CY),Austria,(AT),Sweden,(SE),NaN,NaN,NaN
6,Ireland,(IE),Latvia,(LV),Poland,(PL),NaN,NaN,NaN,NaN,NaN
0,Iceland,(IS),NaN,Norway,(NO),NaN,NaN,NaN,NaN,NaN,NaN
1,Liechtenstein,(LI),NaN,Switzerland,(CH),NaN,NaN,NaN,NaN,NaN,NaN
0,United Kingdom,(UK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Montenegro,(ME),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,North Macedonia,(MK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,(AL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Serbia,(RS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Turkey,(TR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Bosnia and Herzegovina,(BA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kosovo*,(XK[1]),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Armenia,(AM),NaN,Belarus,(BY),NaN,Georgia,(GE),NaN,NaN,NaN
1,Azerbaijan,(AZ),NaN,Moldova,(MD),NaN,Ukraine,(UA),NaN,NaN,NaN
0,Algeria,(DZ),NaN,Lebanon,(LB),NaN,Syria,(SY),NaN,NaN,NaN
1,Egypt,(EG),NaN,Libya,(LY),NaN,Tunisia,(TN),NaN,NaN,NaN
2,Israel,(IL),NaN,Morocco,(MA),NaN,NaN,NaN,NaN,NaN,NaN
3,Jordan,(JO),NaN,Palestine [2],(PS),NaN,NaN,NaN,NaN,NaN,NaN
0,Russia,(RU),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Argentina,(AR),NaN,China (except Hong Kong),(CN_X_HK),NaN,Mexico,(MX),NaN,South Africa,(ZA)
1,Australia,(AU),NaN,Hong Kong,(HK),NaN,Nigeria,(NG),NaN,South Korea,(KR)
2,Brazil,(BR),NaN,India,(IN),NaN,New Zealand,(NZ),NaN,Taiwan,(TW)
3,Canada,(CA),NaN,Japan,(JP),NaN,Singapore,(SG),NaN,United States,(US)

In [81]:
country_names = countries_table[0].append(countries_table[2]).append(countries_table[4]).append(countries_table[6]).append(countries_table[9]).reset_index(drop=True)
country_ids = countries_table[1].append(countries_table[3]).append(countries_table[5]).append(countries_table[7]).append(countries_table[10]).reset_index(drop=True)


full_countries_list =  pd.DataFrame({'Country Name': country_names,'Country ID':country_ids})

full_countries_list

      Country Name Country ID
0          Belgium       (BE)
1         Bulgaria       (BG)
2          Czechia       (CZ)
3          Denmark       (DK)
4          Germany       (DE)
..             ...        ...
135            NaN        NaN
136   South Africa       (ZA)
137    South Korea       (KR)
138         Taiwan       (TW)
139  United States       (US)

[140 rows x 2 columns]

In [146]:
def get_countries():
    url = 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes'
    table_0 = pd.read_html(url)[0]
    table_1 = pd.read_html(url)[1]
    table_2 = pd.read_html(url)[2]
    table_3 = pd.read_html(url)[3]
    table_4 = pd.read_html(url)[4]
    table_5 = pd.read_html(url)[5]
    table_6 = pd.read_html(url)[6]
    table_7 = pd.read_html(url)[7]
    table_8 = pd.read_html(url)[8]

    countries_table = pd.concat([table_0, table_1, table_2, table_3, table_4, table_5, table_6, table_7, table_8])
    
    country_names = countries_table[0].append(countries_table[2]).append(countries_table[4]).append(countries_table[6]).append(countries_table[9]).reset_index(drop=True)
    country_ids = countries_table[1].append(countries_table[3]).append(countries_table[5]).append(countries_table[7]).append(countries_table[10]).reset_index(drop=True)


    full_countries_list =  pd.DataFrame({'Country_Name': country_names,'country_code':country_ids})

    return full_countries_list

In [147]:
new_countries = get_countries()
new_countries

      Country_Name country_code
0          Belgium         (BE)
1         Bulgaria         (BG)
2          Czechia         (CZ)
3          Denmark         (DK)
4          Germany         (DE)
..             ...          ...
135            NaN          NaN
136   South Africa         (ZA)
137    South Korea         (KR)
138         Taiwan         (TW)
139  United States         (US)

[140 rows x 2 columns]

In [95]:
def db_cleaning(db):
    db['gender'] = db['gender'].str.capitalize()
    db['gender'] = db['gender'].str.replace(r'\b[f]\w+', 'female')
    db['gender'] = db['gender'].str.replace(r'\b[m]\w+', 'male')
    return db

db_cleaning(merged_tables)

merged_tables

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,Male,NO,40_65,AT,countryside,no,no,None,I know something about it,I would not vote,None of the above,None of the above,None of the above
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,Male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,Male,nO,26_39,AT,city,None,no,None,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,AT,Country,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Female,yES,40_65,AT,city,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,Female,nO,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...
9646,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,Male,NO,juvenile,SK,Non-Rural,low,no,None,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,Male,yES,40_65,SK,city,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,Female,YES,40_65,SK,city,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...

In [152]:
def countries_clean(countries_df):
    final_countries = countries_df.dropna()
    final_countries['country_code'] = final_countries['country_code'].str.replace("(","")
    final_countries['country_code'] = final_countries['country_code'].str.replace(")","")
    return final_countries

In [154]:
def_countries = countries_clean(new_countries)

<ipython-input-152-a34df4e42aae>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_countries['country_code'] = final_countries['country_code'].str.replace("(","")
<ipython-input-152-a34df4e42aae>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_countries['country_code'] = final_countries['country_code'].str.replace(")","")

In [161]:



result = pd.merge(merged_tables, def_countries, on="country_code")
result

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,Country_Name
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,Male,NO,40_65,AT,countryside,no,no,None,I know something about it,I would not vote,None of the above,None of the above,None of the above,Austria
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,Male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Austria
2,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,Male,nO,26_39,AT,city,None,no,None,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,Austria
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65,AT,Country,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,Austria
4,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Female,yES,40_65,AT,city,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,Austria
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8220,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37 years old,Female,nO,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,‰Û_ spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,Slovakia
8221,39f989f0-db52-0133-8482-0a81e8b09a82,53 years old,Male,yES,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,Slovakia
8222,70ce4a90-d965-0133-f5e4-0a81e8b09a82,1992,Male,NO,juvenile,SK,Non-Rural,low,no,None,I have heard just a little about it,I would not vote,‰Û_ spend more time with my family,It reduces anxiety about financing basic needs,None of the above,Slovakia
8223,2896e440-db3c-0133-5b67-0a81e8b09a82,47 years old,Male,yES,40_65,SK,city,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Slovakia
8224,06217ba0-dd56-0133-edda-0a81e8b09a82,51 years old,Female,YES,40_65,SK,city,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,Slovakia

In [164]:

final_result = pd.merge(result, jobs_defined, on="normalized_job_code")
final_result.head()

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,Country_Name,title,normalized_job_title,parent_uuid
0,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,Male,yES,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Austria,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056
1,cf24ed60-da3f-0133-0034-0a81e8b09a82,48 years old,Female,NO,40_65,AT,Country,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs...,None of the above,Austria,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056
2,9ffc7390-dba5-0133-259b-0a81e8b09a82,43 years old,Male,YES,40_65,BE,Country,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs...,It increases dependence on the state,Belgium,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056
3,a6361230-da58-0133-cd5a-0a81e8b09a82,43 years old,Male,yES,40_65,BE,urban,medium,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote against it,A basic income would not affect my work choices,None of the above,Only the people who need it most should get so...,Belgium,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056
4,1e2b4750-d987-0133-3c7c-0a81e8b09a82,52 years old,Female,YES,40_65,BG,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I have heard just a little about it,I would probably vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,It might encourage people to stop working,Bulgaria,Automatic Data Processing Planner,automatic data processing planner,0148f61d4227497728ce33490843d056

In [207]:
def final_table(main_df, jobs_df, countries_df):
    merged_jobs = pd.merge(main_df, jobs_df, on="normalized_job_code")
    merged_countries = pd.merge(merged_jobs, countries_df, on="country_code")
    merged_countries['Quantity'] = 1
    merged_countries['Percentage'] = 1 / len(merged_countries)
    return merged_countries[['Country_Name', 'title', 'gender', 'Quantity', 'Percentage']]

In [209]:
table = final_table(merged_tables, jobs_defined, def_countries)
table

,Country_Name,title,gender,Quantity,Percentage
0,Austria,Automatic Data Processing Planner,Male,1,0.000203
1,Austria,Automatic Data Processing Planner,Female,1,0.000203
2,Austria,Data Coordinator,Male,1,0.000203
3,Austria,Data Coordinator,Male,1,0.000203
4,Austria,Database Developer,Female,1,0.000203
...,...,...,...,...,...
4921,Malta,Geographic Information Systems Data Administra...,Male,1,0.000203
4922,Malta,Internet Database Specialist,Male,1,0.000203
4923,Malta,Database Coordinator,Male,1,0.000203
4924,Malta,Database Coordinator,Female,1,0.000203
4925,Malta,Data Scientist,Male,1,0.000203

In [203]:
new_table = table.groupby('Country_Name').count()[['gender', 'title']]
new_table

              gender  title
Country_Name
Austria            5      5

In [ ]:
def report(dataframe, country):
    if country is 'ALL':
        
        
    
    
    
    
    pd.read_sql_query(f'select * from {i}', engine) for i in tables_names_lst]

In [ ]:
SELECT Country_Name, 
title AS Job Title, 
gender AS Gender, 
count(uuid) AS Quantity, 
count(uuid) / count AS Percentage 
FROM final_result group by Country_Name;

In [234]:
def report(dataframe, country):
    if country.lower() == 'all':
        reporting = dataframe
        return reporting
    elif (dataframe['Country_Name'] == country.capitalize()).any():
        reporting = dataframe[(dataframe['Country_Name'] == country)]
        return reporting

In [250]:
def report(dataframe, country):
    if country.lower() == 'all':
        reporting = pd.DataFrame(dataframe.groupby(['Country_Name','title', 'gender']).agg({'Quantity':['sum'], 'Percentage':['sum']}).reset_index())
        return reporting
    elif (dataframe['Country_Name'] == country.capitalize()).any():
        reporting = pd.DataFrame(dataframe[(dataframe['Country_Name'] == country)].groupby(['Country_Name','title', 'gender']).agg({'Quantity':['sum'], 'Percentage':['sum']}).reset_index())
        return reporting
    else:
        print('ERROR: Country selected is not in Database')

In [258]:
country_trial = report(table,'Spain')

In [257]:
def to_csv(dataframe):
    dataframe.to_csv('../Output/reporting.csv',index = False)
    return print('Converted to CSV!')

In [259]:
to_csv(country_trial)

Converted to CSV!